### ISSUE TITLE
UI wireframes/mockups

### ISSUE THREAD

**Issue by meerilem** [SuperTurban/ekm_mobiilposm2ng#17]
https://drive.google.com/file/d/0B_I29lJG2gL8MENrLUpOdzJMWnFLcFgxTnoxUEZnSGI3UTFz/view?usp=sharing

**Comment by meerilem** [comment]
If applicable, the application UI has been prototyped using wireframes or mockups and there are links from the detailed requirements to the corresponding UI screens. In the case of a non-interactive application (such as a command-line app), there should be representative examples of "input-output" pairs (instead of UI mockups) and these examples should be linked to the requirements.

**Comment by joelkuppart** [comment]
Created a wiki page which is not yet completed: [Link](https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Prototype)
