### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by meerilem** [SuperTurban/ekm_mobiilposm2ng#18]
Release notes for this iteration are present. Reading the release notes gives an overview what features of the system are supported by the released version of the system and is thus input for the acceptance testing by the customer&course organizer. If delivered functionality contains known bugs, those issues are highlighted in release notes.

**Comment by joelkuppart** [comment]
- [ ] Live environment for the web application
- [ ] Setting up the mobile application (how to access?)
- [ ] All the finished tasks
- [ ] Bugs
