### ISSUE TITLE
Adding a destination point - UI (4h)

### ISSUE THREAD

**Issue by joelkuppart** [SuperTurban/ekm_mobiilposm2ng#27]
**Subtask of:** [https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/12](https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/12)
**What kind of data should the user be able to add:** [UC-2](https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases)

**Comment by SuperTurban** [comment]
Text fields are implemented but image and audio file fields are missing.
