### ISSUE TITLE
Creating an UI for the game creation (3h)

### ISSUE THREAD

**Issue by meerilem** [SuperTurban/ekm_mobiilposm2ng#37]
**Subtask of:** [https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/7](https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/7)

https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases#uc-1---add-a-new-game

**Comment by SuperTurban** [comment]
Needs validation to be implemented.
