### ISSUE TITLE
Create API endpoint to get data about games (3h)

### ISSUE THREAD

**Issue by joelkuppart** [SuperTurban/ekm_mobiilposm2ng#38]
**Subtask of:** [https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/14](https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/14)

**Comment by joelkuppart** [comment]
Returns list of all games.

**Comment by SuperTurban** [comment]
GET /app/game/
