### ISSUE TITLE
Create a project plan scope

### ISSUE THREAD

**Issue by joelkuppart** [SuperTurban/ekm_mobiilposm2ng#4]
- Create issues(tasks) for all functionalities
- Add task descriptions
- Sort the tasks into milestones (iterations 2-4)
- Give each issue a time estimation
- Prioritize issues
- Assign issues

**Comment by joelkuppart** [comment]
List of all issues should be in project plan page: https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Project-plan

**Comment by meerilem** [comment]
Add more detailed tasks and evaluate the scope for all iterations

**Comment by meerilem** [comment]
Iteration 2
The tasks are estimated, and the estimates have been discussed with the customer. The project plan indicates what tasks are delivered in the subsequent iterations. There is a clear picture of what functionality will be ready after iteration 3 and after iteration 4.
