### ISSUE TITLE
Showing destination points as a list (5 h)

### ISSUE THREAD

**Issue by meerilem** [SuperTurban/ekm_mobiilposm2ng#74]
A list with points appear on the sidebar for clarification.
[UC-3](https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases#uc-3---join-a-game)
Sub task of [https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/14](https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/14)

**Comment by kuldar-daniel** [comment]
Done
