### ISSUE TITLE
Destination point displays info (7 h)

### ISSUE THREAD

**Issue by meerilem** [SuperTurban/ekm_mobiilposm2ng#75]
Clicking on a destination point shows name and short description about it
[UC-3](https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases#uc-3---join-a-game)
Sub task of [https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/14](https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/14)

**Comment by kuldar-daniel** [comment]
Done
