### ISSUE TITLE
Create UI for accessing leaderboards in webapp. (7h)

### ISSUE THREAD

**Issue by SuperTurban** [SuperTurban/ekm_mobiilposm2ng#78]
https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases#uc-51---checking-the-leaderboard-on-the-webapp
Subtask of #85

**Comment by joelkuppart** [comment]
Reminders:

- Create DestinationPoints.vue in /clients/src/components

- Give an address to the component in /clients/router/index
