### ISSUE TITLE
Create api endpoints to get leaderboard data. (10h)

### ISSUE THREAD

**Issue by SuperTurban** [SuperTurban/ekm_mobiilposm2ng#80]
https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases#uc-51---checking-the-leaderboard-on-the-webapp

https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases#uc-52---checking-the-leaderboard-on-the-mobile-app

Subtask of #85

**Comment by joelkuppart** [comment]
Takes 1 argument: game ID and returns the game's player scores.

**Comment by joelkuppart** [comment]
API endpoints to query data per a game and all games are working, except one thing: The query always returns usernames as null. Need to fix that.
