### ISSUE TITLE
Make leaderboard tab to mobileapp (5h)

### ISSUE THREAD

**Issue by meerilem** [SuperTurban/ekm_mobiilposm2ng#84]
Sidebar has an extra item "leaderboard", that is clickable
[UC-5.2](https://github.com/SuperTurban/ekm_mobiilposm2ng/wiki/Use-cases#uc-52---checking-the-leaderboard-on-the-mobile-app)
Sub task of [https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/86](https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/86)

**Comment by kuldar-daniel** [comment]
Done
